config/routes.rb
Rails.application.routes.draw do
  # get 'cocktail/ingredient'
  # get 'cocktail/dose'
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :cocktails
  # resources :ingredients
  # resources :doses
  resources :cocktails do
    resources :doses
  end

  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktail = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktails_path(@cocktail)
    else
      render :new
    end

  end

  def update
    respond_to do |format|
      if @dose.update(dose_params)
        format.html { redirect_to @dose, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @dose }
      else
        format.html { render :edit }
        format.json { render json: @dose.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<!--   <div class="simple_form-inputs">
    <%= f.input :name %>
  </div> -->

  <div class="simple_form-inputs"></div>
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <div class="simple_form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to "Add a Recipe" , new_cocktail_dose_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.2) 50%), url('<%= image_path 'bar.jpg' %>');">
  <div class="banner-content">
    <a><%= image_tag 'logo.png' %></a>
    <a class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>
    <div class="container">
      <div class="row">
        <% @cocktail.each do |cocktail| %>
        <div class="col col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
            <%= link_to cocktail_path(cocktail) do  %>
            <h2><%= cocktail.name%></h2>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    <!-- link_to path do-->
    <!-- CLICKABLE -->
    <!-- end -->
    <%= link_to 'New Cocktail', new_cocktail_path %>
    </div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%@cocktail.doses.each do |dose| %>
  <p><%= dose.description %></p>
<% end %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>
<%@cocktail.doses.each do |dose| %>
  <p><%= dose.description %></p>
  <p><%= dose.ingredient.name %></p>
<% end %>
<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to "Add a Recipe" , new_cocktail_dose_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-sm-8 col-sm-offset-2">
      <h1>Add A New Recipe!</h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient, collection: Ingredient.all %>
        <%= link_to "Back", cocktails_path, class: "btn btn-warning"  %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>